# Setup
title: Nathanael Seen
tagline: Personal Website
url: https://www.nathanaelseen.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

include: [_pages]

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

# For math-jax (math notations)
markdown: Kramdown


# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: UA-165726081-1

# Specify the author for blog posts
author:
  name: Nathanael Seen
  url: https://twitter.com/mdo
  email: coderatwork64@gmail.com


# Custom vars
version: 3.0.0
